spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql:serene_cartwright:5432/phat}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: true
    generate-dll: true
    hibernate:
      dll-auto: create